.PHONY: all clean
all: program
main.o: main.c
	gcc -m32 -std=c99 -c -o main.o main.c
func.o: func.asm
	nasm -f elf32 -o func.o func.asm
program: main.o func.o
	gcc -m32 -o program main.o func.o

clean:
	rm *.o program
